trigger:
  - main  # Runs the pipeline when code is pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Uses Microsoft-hosted Ubuntu agent

steps:
  - task: Bash@3
    displayName: "Pull Docker Image"
    inputs:
      targetType: 'inline'
      script: |
        docker pull nginx:latest  # Replace with your desired image
