pool:
  name: 'ganesh'  # Replace with your agent pool name

steps:
  - task: Bash@3
    displayName: 'Run on MyUbuntuAgent'
    inputs:
      targetType: 'inline'
      script: |
        echo "This is running on MyUbuntuAgent!"
