pool:
  name: 'ganesh'  # Your self-hosted agent pool

steps:
  - task: Bash@3
    displayName: 'Clone Git Repository'
    inputs:
      targetType: 'inline'
      script: |
        echo "Cloning repository..."
        git clone   # Replace with your repository URL
        cd <your-repo-name>  # Replace with the name of the directory created by cloning
        echo "Verifying repository files..."
        ls -l  # List the files in the repo to verify it's cloned
        git log -1  # Show the latest commit to verify it's from the main branch
